version: 2.1 #バージョン2.1使用
orbs: #パッケージ（orbs）の中からPython2.0.3を使用
  python: circleci/python@2.0.3
  ruby: circleci/ruby@2.6.0

jobs: #jobの定義（初めの一回のみ） 
  cfn-lint: #jobの名前を設定
    executor: python/default #jobのstepが実行される実行環境を定義（Pythonのデフォルト環境指定）
    steps:
      - checkout #GitHubから情報取得
      - run: pip install cfn-lint #pip(Python用ツール)でcfn-lintをinstall
      - run:
          name: run cfn-lint #実行名を定義（無いと下のコマンドが名前になってみにくくなる）
          command: | #cloudformationフォルダ内の.ymlをテストさせるコマンド
            cfn-lint -i W3002 -t cloudformation/*.yml


  ansible-start: #jobの名前を設定
    executor: python/default #実行環境を定義
    steps: #作業手順
      - checkout #GitHubから情報取得
      - add_ssh_keys:
          fingerprints: #circleCIで登録済み
            - "SHA256:BbF/e4qEHi98IYbVJ7I55VRHsvmm0uEFxdHjsie0Y4g"
    
      - run: #pipでansibleinstall
          name: ansible install
          command: pip install ansible
 
      - run: #実行コマンド
          name: ansible command start
          command: |
            ssh-keyscan $RaiseTech13IP >> ~/.ssh/known_hosts

            ansible-playbook -i ansible/inventory.ini \
            -e "ansible_server_host=$RaiseTech13IP" \
            -e "key_name=/home/circleci/.ssh/id_rsa" \
            ansible/playbook.yml

#＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
  serverspec-start:
    docker:
      - image: cimg/ruby:3.2.3 #ruby3.2.3が入ったdockerを使用
    #executor: ruby/default ※defaultのrubyが古くbundlerが動かなかったので上記に変更した。
    steps: #作業手順
      - checkout #GitHubから情報取得
      - add_ssh_keys:
          fingerprints: #circleCIで登録済み
            - "SHA256:BbF/e4qEHi98IYbVJ7I55VRHsvmm0uEFxdHjsie0Y4g"
    
      #- run: #gemでserverspec install
      #    name: serverspec install
      #    command: gem install serverspec

      #- run: #gemでrake install
      #    name: spec install
      #    command: gem install rake

      - ruby/install-deps: #bundle installをしてくれる
          app-dir: serverspec

      - run: #実行コマンド
          name: serverspec command start
          command: |
            ssh-keyscan $RaiseTech13IP >> ~/.ssh/known_hosts
            cd serverspec
            TARGET_HOST=$RaiseTech13IP bundle exec rake spec

 #=================================================           

workflows: #jobとその実行順序を定義する場所
  raisetech: #ワークフロウの名前を設定
    jobs:
      - cfn-lint
      - ansible-start:
          requires:
            - cfn-lint

      - serverspec-start:
          requires:
            - ansible-start
